### ISSUE TITLE
Typo in Queue.php

### ISSUE THREAD

**Issue by fredy314** [wayhood/yii2-asynctask#2]
> ```
> public function setRetry($data, $score=null)
> {
>     $key = 'retry';
>     if (is_null($score)) {
>         $socre = doubleval(microtime(true));
>     } else {
>         $score = doubleval($score);
>     }
>     return $this->redis->zadd($key, $score, json_encode($data));
> }
> ```

must be
`$score = doubleval(microtime(true));`

**Comment by netyum** [comment]
thanks
